spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
    username: root
    password: 147258
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/*.xml
  type-aliases-package: com.demo1.dao
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080
  tomcat:
    threads:
      max: 200
  error:
    include-exception: true
    include-stacktrace: NEVER

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.yourpackage: DEBUG

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

